# Generated by Django 5.0.4 on 2024-05-11 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sotuv',
            name='sana',
            field=models.DateTimeField(),
        ),
    ]
