# Generated by Django 5.0.4 on 2024-05-11 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mijoz',
            name='oluvchi',
        ),
        migrations.AlterField(
            model_name='mahsulot',
            name='sana',
            field=models.DateField(),
        ),
    ]
